import { Program, NewsItem } from '@/app/types/program';

export const mockPrograms: Program[] = [
  {
    id: '1',
    title: 'Biomedical Engineering Research Program',
    country: 'USA',
    institution: 'Stanford University',
    field: 'bioengineering',
    description: 'Intensive summer research program focusing on tissue engineering and regenerative medicine. Work alongside leading researchers on cutting-edge projects.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 17, max: 22 },
    applicationDeadline: new Date('2026-03-15'),
    programStart: new Date('2026-06-20'),
    duration: '8 weeks',
    applicationCost: 75,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 15,
    requirements: ['GPA 3.5+', 'Biology/Chemistry coursework', 'Letter of recommendation', 'Essay'],
    benefits: ['$3,000 stipend', 'Housing included', 'Lab certification', 'Networking events'],
  },
  {
    id: '2',
    title: 'AI & Machine Learning Bootcamp',
    country: 'UK',
    institution: 'University of Cambridge',
    field: 'computer-science',
    description: 'Comprehensive program covering deep learning, neural networks, and practical AI applications. Build real-world projects with industry mentors.',
    format: 'hybrid',
    residence: 'off-campus',
    ageRange: { min: 18, max: 25 },
    applicationDeadline: new Date('2026-02-28'),
    programStart: new Date('2026-07-01'),
    duration: '6 weeks',
    applicationCost: 100,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 25,
    requirements: ['Programming experience', 'Math proficiency', 'Portfolio', 'Statement of purpose'],
    benefits: ['Certificate', 'Industry connections', 'Project showcase', 'Career guidance'],
  },
  {
    id: '3',
    title: 'Global Business Leadership Summit',
    country: 'Singapore',
    institution: 'National University of Singapore',
    field: 'business',
    description: 'Immersive business program exploring Asian markets, entrepreneurship, and global trade dynamics. Includes company visits and networking.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 19, max: 23 },
    applicationDeadline: new Date('2026-04-01'),
    programStart: new Date('2026-08-10'),
    duration: '4 weeks',
    applicationCost: 50,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 35,
    requirements: ['Interest in business', 'English proficiency', 'Essay', 'Resume'],
    benefits: ['Company visits', 'Networking dinner', 'Certificate', 'Mentorship'],
  },
  {
    id: '4',
    title: 'Digital Arts & Design Intensive',
    country: 'Germany',
    institution: 'Berlin University of the Arts',
    field: 'arts',
    description: 'Creative program exploring digital media, UX/UI design, and interactive installations. Culminates in a public exhibition of student work.',
    format: 'offline',
    residence: 'homestay',
    ageRange: { min: 16, max: 21 },
    applicationDeadline: new Date('2026-03-20'),
    programStart: new Date('2026-07-15'),
    duration: '5 weeks',
    applicationCost: 60,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 40,
    requirements: ['Portfolio submission', 'Artist statement', 'Letter of recommendation'],
    benefits: ['Exhibition opportunity', 'Studio space', 'Materials provided', 'Berlin culture pass'],
  },
  {
    id: '5',
    title: 'Medical Sciences Research Internship',
    country: 'Canada',
    institution: 'University of Toronto',
    field: 'medicine',
    description: 'Hospital-based research program focusing on clinical studies, patient care innovations, and medical technology. Shadow physicians and conduct research.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 23 },
    applicationDeadline: new Date('2026-02-15'),
    programStart: new Date('2026-06-01'),
    duration: '10 weeks',
    applicationCost: 85,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 20,
    requirements: ['Pre-med coursework', 'GPA 3.7+', '2 Letters of recommendation', 'Personal statement'],
    benefits: ['Clinical exposure', 'Research publication opportunity', 'Stipend', 'Housing'],
  },
  {
    id: '6',
    title: 'Sustainable Engineering Workshop',
    country: 'Netherlands',
    institution: 'Delft University of Technology',
    field: 'engineering',
    description: 'Hands-on engineering program focused on renewable energy, sustainable design, and green technologies. Work on real-world sustainability challenges.',
    format: 'offline',
    residence: 'off-campus',
    ageRange: { min: 17, max: 22 },
    applicationDeadline: new Date('2026-03-30'),
    programStart: new Date('2026-07-20'),
    duration: '6 weeks',
    applicationCost: 70,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 30,
    requirements: ['STEM background', 'Essay on sustainability', 'Academic transcript'],
    benefits: ['Lab access', 'Industry partnerships', 'Certificate', 'Bike rental included'],
  },
  {
    id: '7',
    title: 'Data Science & Analytics Program',
    country: 'Australia',
    institution: 'University of Melbourne',
    field: 'computer-science',
    description: 'Comprehensive data science program covering statistics, machine learning, and big data analytics. Real industry datasets and case studies.',
    format: 'online',
    residence: 'not-provided',
    ageRange: { min: 16, max: 24 },
    applicationDeadline: new Date('2026-04-15'),
    programStart: new Date('2026-05-01'),
    duration: '8 weeks',
    applicationCost: 40,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 45,
    requirements: ['Basic programming', 'Math foundation', 'Application form'],
    benefits: ['Certificate', 'Portfolio projects', 'Mentorship', 'Flexible schedule'],
  },
  {
    id: '8',
    title: 'Global Development & Policy',
    country: 'Switzerland',
    institution: 'Graduate Institute Geneva',
    field: 'social-sciences',
    description: 'Explore international relations, development economics, and policy-making. Visit UN agencies and engage with global leaders.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 19, max: 23 },
    applicationDeadline: new Date('2026-03-10'),
    programStart: new Date('2026-07-05'),
    duration: '4 weeks',
    applicationCost: 90,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 28,
    requirements: ['Social sciences interest', 'Essay', 'Academic transcript', 'Language proficiency'],
    benefits: ['UN visits', 'Networking events', 'Certificate', 'Travel stipend'],
  },
  {
    id: '9',
    title: 'Marine Biology Field Research',
    country: 'New Zealand',
    institution: 'University of Otago',
    field: 'natural-sciences',
    description: 'Field research program studying marine ecosystems, conservation, and biodiversity. Includes diving certification and boat-based research.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 17, max: 22 },
    applicationDeadline: new Date('2026-02-20'),
    programStart: new Date('2026-06-15'),
    duration: '7 weeks',
    applicationCost: 80,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 32,
    requirements: ['Biology coursework', 'Swimming proficiency', 'Statement of interest', 'Letter of recommendation'],
    benefits: ['Diving certification', 'Research publication', 'Field equipment', 'Accommodation'],
  },
  {
    id: '10',
    title: 'Philosophy & Ethics Summer School',
    country: 'France',
    institution: 'Sorbonne University',
    field: 'humanities',
    description: 'Intensive philosophy program exploring ethics, political philosophy, and existentialism. Seminars with renowned philosophers and cultural excursions.',
    format: 'offline',
    residence: 'homestay',
    ageRange: { min: 17, max: 23 },
    applicationDeadline: new Date('2026-03-25'),
    programStart: new Date('2026-07-10'),
    duration: '5 weeks',
    applicationCost: 55,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 38,
    requirements: ['Essay on philosophical topic', 'Reading list completion', 'Academic transcript'],
    benefits: ['Museum passes', 'Cultural excursions', 'Certificate', 'Book allowance'],
  },
  {
    id: '11',
    title: 'Robotics & Automation Lab',
    country: 'Japan',
    institution: 'Tokyo Institute of Technology',
    field: 'engineering',
    description: 'Cutting-edge robotics program covering AI integration, mechatronics, and autonomous systems. Build and program your own robot.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 23 },
    applicationDeadline: new Date('2026-02-28'),
    programStart: new Date('2026-06-25'),
    duration: '6 weeks',
    applicationCost: 95,
    hasLowIncomeDiscount: false,
    internationalAcceptanceRate: 22,
    requirements: ['Engineering/CS background', 'Portfolio', 'Technical essay', '2 recommendations'],
    benefits: ['Robot kit', 'Lab access', 'Competition entry', 'Industry connections'],
  },
  {
    id: '12',
    title: 'Creative Writing & Publishing',
    country: 'Ireland',
    institution: 'Trinity College Dublin',
    field: 'humanities',
    description: 'Workshop-based writing program covering fiction, non-fiction, and poetry. Work with published authors and learn about the publishing industry.',
    format: 'hybrid',
    residence: 'off-campus',
    ageRange: { min: 16, max: 22 },
    applicationDeadline: new Date('2026-04-10'),
    programStart: new Date('2026-07-15'),
    duration: '4 weeks',
    applicationCost: 50,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 42,
    requirements: ['Writing samples', 'Statement of purpose', 'Reading commitment'],
    benefits: ['Published anthology', 'Author mentorship', 'Literary tours', 'Certificate'],
  },
  {
    id: '13',
    title: 'Climate Science & Sustainability Lab',
    country: 'Germany',
    institution: 'Technical University of Munich',
    field: 'natural-sciences',
    description: 'Research-intensive program studying climate change, environmental modeling, and sustainability solutions. Collaborate with leading climate scientists.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-03-05'),
    programStart: new Date('2026-07-08'),
    duration: '9 weeks',
    applicationCost: 75,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 24,
    requirements: ['Environmental science background', 'Research proposal', 'GPA 3.6+', 'Letter of recommendation'],
    benefits: ['Research stipend', 'Conference attendance', 'Lab certification', 'Housing included'],
  },
  {
    id: '14',
    title: 'Entrepreneurship & Startup Incubator',
    country: 'USA',
    institution: 'MIT',
    field: 'business',
    description: 'Transform your business idea into a viable startup. Access to mentors, investors, and MIT resources. Pitch competition with seed funding prizes.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 19, max: 25 },
    applicationDeadline: new Date('2026-02-10'),
    programStart: new Date('2026-06-10'),
    duration: '12 weeks',
    applicationCost: 120,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 18,
    requirements: ['Business plan', 'Video pitch', 'Resume', 'Two recommendations'],
    benefits: ['$10,000 potential seed funding', 'Investor network', 'Office space', 'Legal support'],
  },
  {
    id: '15',
    title: 'Cybersecurity & Ethical Hacking',
    country: 'UK',
    institution: 'University of Oxford',
    field: 'computer-science',
    description: 'Advanced cybersecurity program covering penetration testing, cryptography, and network security. Hands-on labs with real-world scenarios.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 23 },
    applicationDeadline: new Date('2026-03-15'),
    programStart: new Date('2026-07-01'),
    duration: '6 weeks',
    applicationCost: 110,
    hasLowIncomeDiscount: false,
    internationalAcceptanceRate: 20,
    requirements: ['Programming skills', 'Networking knowledge', 'Technical assessment', 'Essay'],
    benefits: ['Industry certification', 'Lab access', 'Career placement support', 'Networking events'],
  },
  {
    id: '16',
    title: 'Film Production & Cinematography',
    country: 'Australia',
    institution: 'Australian Film School',
    field: 'arts',
    description: 'Hands-on filmmaking program covering directing, cinematography, editing, and production. Create your own short film with professional equipment.',
    format: 'offline',
    residence: 'off-campus',
    ageRange: { min: 17, max: 22 },
    applicationDeadline: new Date('2026-04-20'),
    programStart: new Date('2026-08-05'),
    duration: '5 weeks',
    applicationCost: 65,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 36,
    requirements: ['Portfolio/reel', 'Director statement', 'Creative essay'],
    benefits: ['Film festival submission', 'Equipment access', 'Industry mentors', 'Screening event'],
  },
  {
    id: '17',
    title: 'Neuroscience Research Experience',
    country: 'USA',
    institution: 'Harvard University',
    field: 'medicine',
    description: 'Cutting-edge neuroscience research program focusing on brain imaging, cognitive neuroscience, and neural disorders. Work in world-class labs.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 23 },
    applicationDeadline: new Date('2026-02-05'),
    programStart: new Date('2026-06-15'),
    duration: '10 weeks',
    applicationCost: 100,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 12,
    requirements: ['Neuroscience/Biology coursework', 'GPA 3.8+', 'Research experience', 'Two recommendations'],
    benefits: ['$4,000 stipend', 'Publication opportunity', 'Lab techniques certification', 'Housing'],
  },
  {
    id: '18',
    title: 'International Law & Human Rights',
    country: 'Netherlands',
    institution: 'Leiden University',
    field: 'social-sciences',
    description: 'Explore international law, human rights frameworks, and global justice systems. Mock trials and visits to international courts.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 19, max: 24 },
    applicationDeadline: new Date('2026-03-18'),
    programStart: new Date('2026-07-12'),
    duration: '4 weeks',
    applicationCost: 70,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 30,
    requirements: ['Interest in law/politics', 'Essay', 'Academic transcript', 'English proficiency'],
    benefits: ['Court visits', 'Certificate', 'Networking dinner', 'Legal writing workshop'],
  },
  {
    id: '19',
    title: 'Quantum Computing Fundamentals',
    country: 'Canada',
    institution: 'University of Waterloo',
    field: 'computer-science',
    description: 'Introduction to quantum computing, quantum algorithms, and quantum information theory. Access to quantum computers and simulators.',
    format: 'hybrid',
    residence: 'off-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-03-25'),
    programStart: new Date('2026-06-30'),
    duration: '7 weeks',
    applicationCost: 85,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 26,
    requirements: ['Advanced math', 'Physics knowledge', 'Programming skills', 'Technical essay'],
    benefits: ['Quantum lab access', 'Certificate', 'Research project', 'Industry connections'],
  },
  {
    id: '20',
    title: 'Psychology & Behavioral Science',
    country: 'Switzerland',
    institution: 'University of Zurich',
    field: 'social-sciences',
    description: 'Explore cognitive psychology, behavioral economics, and research methods. Conduct experiments and analyze human behavior patterns.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 17, max: 22 },
    applicationDeadline: new Date('2026-03-28'),
    programStart: new Date('2026-07-20'),
    duration: '5 weeks',
    applicationCost: 80,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 34,
    requirements: ['Psychology coursework', 'Research interest statement', 'Academic transcript'],
    benefits: ['Lab experience', 'Certificate', 'Research methods training', 'Conference attendance'],
  },
  {
    id: '21',
    title: 'Renewable Energy Engineering',
    country: 'Singapore',
    institution: 'Nanyang Technological University',
    field: 'engineering',
    description: 'Focus on solar, wind, and battery technologies. Design and build renewable energy systems with industry-standard tools.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 23 },
    applicationDeadline: new Date('2026-03-01'),
    programStart: new Date('2026-07-05'),
    duration: '8 weeks',
    applicationCost: 75,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 28,
    requirements: ['Engineering/Physics background', 'Technical portfolio', 'Essay on sustainability'],
    benefits: ['Industry site visits', 'Certification', 'Project showcase', 'Networking'],
  },
  {
    id: '22',
    title: 'Archaeology Field School',
    country: 'France',
    institution: 'University of Paris',
    field: 'humanities',
    description: 'Hands-on archaeological excavation experience. Learn field techniques, artifact analysis, and historical research at active dig sites.',
    format: 'offline',
    residence: 'homestay',
    ageRange: { min: 17, max: 23 },
    applicationDeadline: new Date('2026-04-05'),
    programStart: new Date('2026-07-25'),
    duration: '6 weeks',
    applicationCost: 60,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 40,
    requirements: ['History/Anthropology interest', 'Physical fitness', 'Statement of purpose'],
    benefits: ['Field experience', 'Museum visits', 'Certificate', 'Research credit'],
  },
  {
    id: '23',
    title: 'Game Development & Design',
    country: 'Japan',
    institution: 'DigiPen Institute Tokyo',
    field: 'computer-science',
    description: 'Create your own video game from concept to playable prototype. Learn Unity, game design principles, and industry workflows.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 16, max: 22 },
    applicationDeadline: new Date('2026-04-12'),
    programStart: new Date('2026-08-01'),
    duration: '6 weeks',
    applicationCost: 90,
    hasLowIncomeDiscount: false,
    internationalAcceptanceRate: 35,
    requirements: ['Basic programming', 'Game design document', 'Portfolio', 'Creative essay'],
    benefits: ['Published game', 'Industry mentorship', 'Software licenses', 'Demo day presentation'],
  },
  {
    id: '24',
    title: 'Public Health & Epidemiology',
    country: 'UK',
    institution: 'London School of Hygiene',
    field: 'medicine',
    description: 'Study disease prevention, health policy, and epidemiological methods. Analyze real public health challenges and propose solutions.',
    format: 'hybrid',
    residence: 'off-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-03-08'),
    programStart: new Date('2026-06-20'),
    duration: '7 weeks',
    applicationCost: 70,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 32,
    requirements: ['Biology/Statistics background', 'Statement of purpose', 'Academic transcript'],
    benefits: ['Certificate', 'WHO collaboration project', 'Field visits', 'Career guidance'],
  },
  {
    id: '25',
    title: 'Mathematical Modeling & Simulation',
    country: 'Germany',
    institution: 'University of Heidelberg',
    field: 'natural-sciences',
    description: 'Apply advanced mathematics to real-world problems in physics, biology, and economics. Develop computational models and simulations.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-02-25'),
    programStart: new Date('2026-06-28'),
    duration: '8 weeks',
    applicationCost: 65,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 27,
    requirements: ['Advanced math', 'Programming experience', 'Research proposal', 'Recommendation'],
    benefits: ['Research publication', 'Supercomputer access', 'Conference presentation', 'Housing'],
  },
  {
    id: '26',
    title: 'Fashion Design & Textile Innovation',
    country: 'France',
    institution: 'École de la Chambre Syndicale',
    field: 'arts',
    description: 'Learn haute couture techniques, sustainable fashion, and textile technology. Create your own collection for a runway show.',
    format: 'offline',
    residence: 'off-campus',
    ageRange: { min: 17, max: 23 },
    applicationDeadline: new Date('2026-04-15'),
    programStart: new Date('2026-07-18'),
    duration: '5 weeks',
    applicationCost: 95,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 38,
    requirements: ['Design portfolio', 'Creative statement', 'Sewing experience preferred'],
    benefits: ['Runway show', 'Fashion week tickets', 'Industry connections', 'Materials provided'],
  },
  {
    id: '27',
    title: 'Aerospace Engineering Workshop',
    country: 'USA',
    institution: 'Caltech',
    field: 'engineering',
    description: 'Design, build, and test aerospace systems. Topics include aerodynamics, propulsion, and spacecraft design with JPL facility access.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 23 },
    applicationDeadline: new Date('2026-02-18'),
    programStart: new Date('2026-06-22'),
    duration: '9 weeks',
    applicationCost: 110,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 16,
    requirements: ['Physics/Math strong background', 'GPA 3.7+', 'Technical essay', 'Two recommendations'],
    benefits: ['JPL tour', 'NASA connections', 'Flight test', 'Research certificate'],
  },
  {
    id: '28',
    title: 'Financial Markets & Trading',
    country: 'Singapore',
    institution: 'Singapore Management University',
    field: 'business',
    description: 'Learn investment strategies, risk management, and financial analysis. Access to trading simulators and market data platforms.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 19, max: 24 },
    applicationDeadline: new Date('2026-03-12'),
    programStart: new Date('2026-07-22'),
    duration: '5 weeks',
    applicationCost: 85,
    hasLowIncomeDiscount: false,
    internationalAcceptanceRate: 30,
    requirements: ['Economics/Math background', 'Essay', 'Resume', 'Academic transcript'],
    benefits: ['Trading certification', 'Bloomberg terminal access', 'Industry mentors', 'Networking events'],
  },
  {
    id: '29',
    title: 'Genetics & Genomics Research',
    country: 'Canada',
    institution: 'McGill University',
    field: 'bioengineering',
    description: 'Explore gene editing, genomic sequencing, and precision medicine. Work with CRISPR technology and modern genetic analysis tools.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 23 },
    applicationDeadline: new Date('2026-02-22'),
    programStart: new Date('2026-06-18'),
    duration: '10 weeks',
    applicationCost: 80,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 19,
    requirements: ['Molecular biology background', 'GPA 3.6+', 'Research statement', 'Two recommendations'],
    benefits: ['$3,500 stipend', 'Publication opportunity', 'Lab certification', 'Housing'],
  },
  {
    id: '30',
    title: 'Sociology & Urban Studies',
    country: 'Netherlands',
    institution: 'University of Amsterdam',
    field: 'social-sciences',
    description: 'Study urban development, social inequality, and community organization. Conduct fieldwork in Amsterdam neighborhoods.',
    format: 'offline',
    residence: 'off-campus',
    ageRange: { min: 17, max: 23 },
    applicationDeadline: new Date('2026-03-30'),
    programStart: new Date('2026-07-15'),
    duration: '6 weeks',
    applicationCost: 55,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 36,
    requirements: ['Social sciences interest', 'Research proposal', 'Academic transcript'],
    benefits: ['Field research experience', 'Certificate', 'City tours', 'Research methods training'],
  },
  {
    id: '31',
    title: 'Music Production & Audio Engineering',
    country: 'UK',
    institution: 'Abbey Road Institute',
    field: 'arts',
    description: 'Professional music production program covering recording, mixing, mastering, and sound design. Access to world-class studios.',
    format: 'offline',
    residence: 'off-campus',
    ageRange: { min: 17, max: 24 },
    applicationDeadline: new Date('2026-04-18'),
    programStart: new Date('2026-07-28'),
    duration: '6 weeks',
    applicationCost: 100,
    hasLowIncomeDiscount: false,
    internationalAcceptanceRate: 34,
    requirements: ['Music portfolio', 'Technical aptitude', 'Creative statement'],
    benefits: ['Studio time', 'Industry certification', 'Artist collaborations', 'Demo production'],
  },
  {
    id: '32',
    title: 'Artificial Intelligence Ethics',
    country: 'Switzerland',
    institution: 'ETH Zurich',
    field: 'computer-science',
    description: 'Explore ethical implications of AI, algorithmic bias, and responsible technology development. Interdisciplinary approach combining tech and philosophy.',
    format: 'hybrid',
    residence: 'on-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-03-20'),
    programStart: new Date('2026-07-10'),
    duration: '5 weeks',
    applicationCost: 75,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 29,
    requirements: ['AI/Ethics background', 'Position paper', 'Academic transcript'],
    benefits: ['Certificate', 'Policy workshop', 'Tech company visits', 'Publication opportunity'],
  },
  {
    id: '33',
    title: 'Veterinary Medicine & Animal Care',
    country: 'Australia',
    institution: 'University of Sydney',
    field: 'medicine',
    description: 'Hands-on veterinary experience including animal surgery observation, diagnostics, and wildlife conservation. Work with diverse animal species.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 17, max: 22 },
    applicationDeadline: new Date('2026-03-15'),
    programStart: new Date('2026-07-05'),
    duration: '8 weeks',
    applicationCost: 70,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 31,
    requirements: ['Biology background', 'Animal handling experience', 'Statement of purpose', 'Recommendation'],
    benefits: ['Clinical exposure', 'Wildlife fieldwork', 'Certificate', 'Housing included'],
  },
  {
    id: '34',
    title: 'Political Science & Diplomacy',
    country: 'USA',
    institution: 'Georgetown University',
    field: 'social-sciences',
    description: 'Study international relations, political theory, and diplomatic practice. Participate in Model UN and meet with policymakers.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-02-28'),
    programStart: new Date('2026-06-25'),
    duration: '6 weeks',
    applicationCost: 90,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 26,
    requirements: ['Political science interest', 'Essay on global issue', 'Academic transcript', 'Recommendation'],
    benefits: ['Capitol Hill visit', 'Embassy tours', 'Model UN participation', 'Certificate'],
  },
  {
    id: '35',
    title: 'Nanotechnology & Materials Science',
    country: 'Japan',
    institution: 'University of Tokyo',
    field: 'engineering',
    description: 'Explore nanoscale engineering, advanced materials, and molecular manipulation. Access to electron microscopes and cleanroom facilities.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-02-20'),
    programStart: new Date('2026-06-18'),
    duration: '8 weeks',
    applicationCost: 95,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 22,
    requirements: ['Chemistry/Physics background', 'GPA 3.6+', 'Research proposal', 'Two recommendations'],
    benefits: ['Lab certification', 'Research publication', 'Conference attendance', 'Housing'],
  },
];

export const mockNews: NewsItem[] = [
  {
    id: '1',
    title: 'Stanford Biomedical Program - Applications Close in 5 Days',
    description: 'Final deadline: March 15. Complete your essay and recommendation letters now.',
    date: new Date('2026-01-21'),
    type: 'deadline',
    programId: '1',
  },
  {
    id: '2',
    title: 'Updated Requirements for Cambridge AI Bootcamp',
    description: 'New prerequisite added: basic Python knowledge required. Portfolio guidelines updated with code examples.',
    date: new Date('2026-01-20'),
    type: 'announcement',
    programId: '2',
  },
  {
    id: '3',
    title: 'Essay Writing Tip: Avoid Generic Opening Statements',
    description: 'Starting with "Ever since I was young..." or "In today\'s world..." weakens your essay. Open with a specific moment or observation that reveals your unique perspective.',
    date: new Date('2026-01-20'),
    type: 'essay-tip',
  },
  {
    id: '4',
    title: 'Marine Biology Program - Early Application Bonus',
    description: 'Applications submitted by February 1st receive priority review. Decisions released 2 weeks earlier.',
    date: new Date('2026-01-19'),
    type: 'deadline',
    programId: '9',
  },
  {
    id: '5',
    title: 'New Essay Prompt Added for NUS Business Summit',
    description: 'Supplemental essay question: "Describe a business challenge in your community and your proposed solution." (300 words max)',
    date: new Date('2026-01-19'),
    type: 'announcement',
    programId: '3',
  },
  {
    id: '6',
    title: 'Essay Writing Tip: Show Intellectual Curiosity',
    description: 'Committees look for students who ask questions. Instead of stating what you know, explain what you want to discover and why it matters to you.',
    date: new Date('2026-01-18'),
    type: 'essay-tip',
  },
  {
    id: '7',
    title: 'Robotics Lab Tokyo - Application Fee Waiver Available',
    description: 'Students from developing countries can request fee waiver. Submit request form by February 20.',
    date: new Date('2026-01-18'),
    type: 'announcement',
    programId: '11',
  },
  {
    id: '8',
    title: 'Essay Writing Tip: The "Why This Program?" Formula',
    description: 'Connect specific program features to your goals. Formula: "Because [program offers X], I can [achieve Y], which connects to my goal of [Z]."',
    date: new Date('2026-01-17'),
    type: 'essay-tip',
  },
  {
    id: '9',
    title: 'Deadline Alert: Multiple Programs Close February 28',
    description: '3 programs have the same deadline. Prioritize based on acceptance rates and your readiness. Use our AI essay tool to speed up revisions.',
    date: new Date('2026-01-21'),
    type: 'deadline',
  },
  {
    id: '10',
    title: 'Essay Writing Tip: Word Limit Strategy',
    description: 'At 90% of word limit, stop adding. Use remaining space for precision: replace weak verbs, cut filler words, strengthen your thesis.',
    date: new Date('2026-01-19'),
    type: 'essay-tip',
  },
];